# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: su

steps:

- task: AzureWebApp@1  # Azure'daki web hizmetine gönderen görev
  inputs:
    azureSubscription: 'subaskaynak07'
    appName: 'Azure-subaskaynak07'
    package: '$(System.DefaultWorkingDirectory)' # Klasördeki her şeyi gönder

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
